# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/java?view=azure-devops

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: AzureCLI@2
  inputs:
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    scriptPath: 'test.ps1'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    appType: 'webAppContainer'
    WebAppName: 'myappService'
    DockerNamespace: 'myregistry.azurecr.io'
    DockerRepository: 'nginx'
    DockerImageTag: 'latest'
    StartupCommand: 'start.sh'
    AppSettings: |
      -Port 5000 
      -RequestTimeout 5000
      -WEBSITE_TIME_ZONE "Eastern Standard Time"
    ConfigurationSettings: |
      -phpVersion 5.6 
      -linuxFxVersion: node|6.11